/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Book_go.java
 *
 * Created on Dec 28, 2011, 2:43:21 PM
 */

package crescendo_infomedia;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;
/**
 *
 * @author student
 */
public class Book_go extends javax.swing.JFrame {
DefaultTableModel tm;
Connection cn;
ResultSet rs;
Statement st;



  Books ob = new Books();
    /** Creates new form Book_go */
    public Book_go() {
        initComponents();
       try{
          Class.forName("com.mysql.jdbc.Driver");
          cn=DriverManager.getConnection("jdbc:mysql://localhost/crescendo_infomedia" ,"root","dips");
          st=cn.createStatement();
         }
         catch(Exception e)
         {JOptionPane.showMessageDialog(null, e.getMessage());}

        tm=(DefaultTableModel)jTable1.getModel();
   


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Category", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add to cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(96, 96, 96)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(116, 116, 116)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(67, 67, 67)
                        .add(jButton1)
                        .add(40, 40, 40)
                        .add(jButton2)
                        .add(46, 46, 46)
                        .add(jButton3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1)
                    .add(jButton3))
                .add(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jLabel2.setText("LIST OF " + ALLMEDIA.prod.toUpperCase());
        
String ca="";
        if(ALLMEDIA.prod.equals("book"))
        {
            if (ALLMEDIA.ctb == 0)
            {ca = "Fiction";
            }
            else if (ALLMEDIA.ctb == 1)
            {ca = "Suspense";
            }
            else if (ALLMEDIA.ctb == 2)
            {ca = "Drama";
            }
            else if (ALLMEDIA.ctb == 3)
            {ca = "Philosophy";
            }
            else if (ALLMEDIA.ctb == 4)
            {ca = "Comedy";
            }
        }
        
        else if(ALLMEDIA.prod.equals("movie"))
        {
            if (ALLMEDIA.ctb == 0)
            {ca = "Comedy";
            }
            else if (ALLMEDIA.ctb == 1)
            {ca = "Science Fiction";
            }
            else if (ALLMEDIA.ctb == 2)
            {ca = "Horror";
            }
            else if (ALLMEDIA.ctb == 3)
            {ca = "Action";
            }
            else if (ALLMEDIA.ctb == 4)
            {ca = "Mystery";
            }
        
        }
        
        else if(ALLMEDIA.prod.equals("software"))
        {
            if (ALLMEDIA.ctb == 0)
            {ca = "Browser";
            }
            else if (ALLMEDIA.ctb == 1)
            {ca = "Games";
            }
            else if (ALLMEDIA.ctb == 2)
            {ca = "Antivirus";
            }
            else if (ALLMEDIA.ctb == 3)
            {ca = "IDE";
            }
            else if (ALLMEDIA.ctb == 4)
            {ca = "Media";
            }
        
        }

       
        


        try{
        rs=st.executeQuery("select * from " + ALLMEDIA.prod + " where category = "+"'"+ ca +"'");
       }
       catch(Exception e)
         {JOptionPane.showMessageDialog(this, e.getMessage());}
        int prodid=0;
        float price=0F;
        String name = "",category="";

      try{  while(rs.next())
        {
        if(ALLMEDIA.prod.equals("book"))
            {prodid=rs.getInt("Book_ID");
            price=rs.getFloat("Price");
            name=rs.getString("name");
            category=rs.getString("category");
            }
        else if(ALLMEDIA.prod.equals("movie"))
            {prodid=rs.getInt("Movie_ID");
            price=rs.getFloat("Price");
            name=rs.getString("name");
            category=rs.getString("category");
            }
        else if(ALLMEDIA.prod.equals("software"))
            {prodid=rs.getInt("Software_ID");
            price=rs.getFloat("Price");
            name=rs.getString("name");
            category=rs.getString("category");
            }
         
      Object ob1[]={prodid,name,category, price};
      tm.addRow(ob1);
        }
      }
      catch(Exception e)
      {JOptionPane.showMessageDialog(this, e.getMessage());}

        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(ALLMEDIA.last == 4)
        {Books o=new Books();
        o.setVisible(true);}
        else if(ALLMEDIA.last == 5)
        {Movies o=new Movies();
        o.setVisible(true);}
        if(ALLMEDIA.last == 6)
        {Softwares o=new Softwares();
        o.setVisible(true);}
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    Buy oj =new Buy();
    ALLMEDIA.last = 0;
    oj.setVisible(true);
    this.dispose();

}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    int r = jTable1.getSelectedRow();
    
    if(ALLMEDIA.cart_count<=10)
    {
  Object oj[] = {tm.getValueAt(r, 0),tm.getValueAt(r, 1),tm.getValueAt(r, 2),tm.getValueAt(r, 3),};
  ALLMEDIA.o[ALLMEDIA.cart_count]=oj;
   ALLMEDIA.cart_count++;
   
    }
    else{JOptionPane.showMessageDialog(null, "Maximum 10 items in the cart only! ");}

}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_go().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
